### ISSUE TITLE
Set max pool size

### ISSUE THREAD

**Issue by esakik** [esakik/beam-mysql-connector#1]

**Comment by binitharajv** [comment]
Hi esaki01 ,
I tried to use WriteToMySQL to write records from pubsub topic to cloud mysql through dataflow .When I execute the pipeline ,I am getting the error " raise MySQLClientError(f"Failed to connect mysql, Raise exception: {e}")
beam_mysql.connector.errors.MySQLClientError: Failed to connect mysql, Raise exception: 2003 (HY000): Can't connect to MySQL server on 'localhost' (99) [while running 'WriteToMysql/ParDo(_WriteToMySQLFn)']" . Should i run additional file as part of set up ?Kindly reply

**Comment by esakik** [comment]
Hi binitharajv,

You can set up a VPN for dataflow workers because these have not external IP address.
Also, it's needed that cloud mysql allow the IP address.

Ref: https://stackoverflow.com/questions/35011705/google-cloud-platform-dataflow-workers-ip-addresses
