### ISSUE TITLE
Bulk Insert to MySql

### ISSUE THREAD

**Issue by anzshul** [esakik/beam-mysql-connector#12]
Hi,
I am using the connector to write to MySql using batch size as 1000,but I get error suggesting to use bulk Insert with cmd_insert option. 
Could you please share few examples with bulk Insert?The example provided uses insert option with batch size as 0.
Thanks!

**Comment by nlenepveu** [comment]
This change will fix your problem: https://github.com/esakik/beam-mysql-connector/pull/16
