### ISSUE TITLE
AttributeError: 'NoSplitter' object has no attribute 'source'

### ISSUE THREAD

**Issue by susumuasaga** [esakik/beam-mysql-connector#6]
I still getting 'NoiSplitter' object has no attribute 'source', even on version 1.8.2.
In order to get it running, I had to do a makeshift change in the code of splitter.py:
```python
class NoSplitter(BaseSplitter):
    """No split bounded source so not work parallel."""

    def estimate_size(self):
        # return self.source.client.rough_counts_estimator(self.source.query)
        return 0x100000 # may be any number
```

**Comment by esakik** [comment]
@susumuasaga 
I'm sorry to reply late.
@mkdotam patched this issue and I released version 1.8.3.
